---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: span-mirror-ovs-exec
  namespace: ovn-kubernetes
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: span-mirror-ovs-exec
  namespace: ovn-kubernetes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: span-mirror-ovs-exec
subjects:
- kind: ServiceAccount
  name: span-mirror-controller
  namespace: kube-system
